sonar.organization=atomatom148-dotcom
sonar.projectKey=atomatom148-dotcom_ATOM

sonar.sources=quant
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
