from dataclasses import asdict, replace
from datetime import datetime, timedelta, timezone
import math
import json
import random

import pytest

from quant.v9_v1_contract import HORIZONS, HORIZON_SECONDS
from quant.v9_v3_synthesis import V3HorizonResult
from quant.v9_v4a_evidence import (
    ForecastRecord, OutcomeRecord, canonical_sha256, select_non_overlapping,
    _canonical,
)
from quant.v9_v4b_accuracy import (
    BETA_X_TOLERANCE, JEFFREYS_METHOD, MODEL_VERSION, STATE_VERSION,
    AccuracyStateStore, build_accuracy_state,
    effective_n, final_numbers, inverse_regularized_incomplete_beta,
    governed_accuracy_evidence, regularized_incomplete_beta,
)

UTC = timezone.utc
NOW = datetime(2026, 1, 1, tzinfo=UTC)


def v3(value, status="AVAILABLE"):
    return V3HorizonResult("1M",60,value,None,status,(),(),0,None)


def forecast(horizon, i, mu, cohort="cohort"):
    cutoff=NOW+timedelta(seconds=i*HORIZON_SECONDS[horizon])
    raw=ForecastRecord(f"f-{horizon}-{i}","a"*64,"ATOM_TRUE_V9_V4_1",
        "ATOM_TRUE_V9_V4A_1","PRODUCTION",cohort,"b"*64,"COIN",cutoff,
        cutoff+timedelta(seconds=HORIZON_SECONDS[horizon]),horizon,HORIZON_SECONDS[horizon],
        str(i),None,"ATOM-TRUE-V9-V3","v2","v2","c"*64,0.0,mu,None,None,
        "AVAILABLE",(),cutoff,True,None)
    return raw


def outcome(f, y, eligible=True):
    return OutcomeRecord(f"o-{f.forecast_record_id}","d"*64,"ATOM_TRUE_V9_V4_1",
        "ATOM_TRUE_V9_V4A_1",f.forecast_record_id,"target",f.target_endpoint,
        f.target_endpoint,0.0,f.target_endpoint,y,"VERIFIED" if eligible else "UNVERIFIED",
        (),eligible,f.target_endpoint)


def cohorts(): return {h:("cohort","b"*64) for h in HORIZONS}


def test_final_numbers_exact_mu_expm1_direction_and_absent_accuracy():
    for value,direction in ((25.0,"EXPECTED_UP"),(-25.0,"EXPECTED_DOWN"),(0.0,"EXPECTED_FLAT")):
        got=final_numbers(v3(value))
        assert got.final_bps == value
        assert got.move_percent == 100*math.expm1(value/10000)
        assert got.direction == direction and got.accuracy is None
    got=final_numbers(v3(None,"UNAVAILABLE"))
    assert got.final_bps is None and got.move_percent is None and got.direction == "UNAVAILABLE"
    assert final_numbers(v3(1e308)).final_bps == 1e308
    assert final_numbers(v3(1e308)).move_percent is None


@pytest.mark.parametrize("a,b,p,expected",[
    (.5,.5,.025,0.001541333133436012),(.5,.5,.975,0.998458666866564),
    (1,1,.025,.025),(1,1,.975,.975),
    (2,2,.025,0.09429932405024608),(2,2,.975,0.9057006759497539),
    (2,5,.025,0.043271868292741676),(2,5,.975,0.6412345789976748),
    (3.25,7.75,.025,0.0793344714875275),(3.25,7.75,.975,0.581369241779612),
])
def test_beta_independent_reference_fixtures(a,b,p,expected):
    # Reference values are fixed high-precision values (not generated by this module).
    q=inverse_regularized_incomplete_beta(a,b,p)
    assert q == pytest.approx(expected,abs=2e-11)
    assert regularized_incomplete_beta(a,b,q) == pytest.approx(p,abs=1e-12)
    assert math.isfinite(q)


def test_beta_symmetry_monotonic_boundaries_repeatability():
    values=[inverse_regularized_incomplete_beta(.5,4,p) for p in (1e-10,.025,.5,.975,1-1e-10)]
    assert values == sorted(values)
    assert inverse_regularized_incomplete_beta(2,5,.025) == inverse_regularized_incomplete_beta(2,5,.025)
    assert inverse_regularized_incomplete_beta(2,5,.025) == pytest.approx(
        1-inverse_regularized_incomplete_beta(5,2,.975),abs=2*BETA_X_TOLERANCE)
    assert inverse_regularized_incomplete_beta(1,1,0)==0
    assert inverse_regularized_incomplete_beta(1,1,1)==1


def test_metrics_zero_conventions_hash_order_and_immutability():
    samples=[(2.0,1.0),(-1.0,-3.0),(0.0,2.0),(9.0,0.0)]
    evidence=[]
    for i,(mu,y) in enumerate(samples):
        f=forecast("1M",i,mu); evidence.append((f,outcome(f,y)))
    state=build_accuracy_state(symbol="COIN",state_as_of=NOW+timedelta(days=1),
                               cohorts=cohorts(),evidence=evidence)
    h=state.horizon_states[1]
    assert tuple(x.horizon for x in state.horizon_states)==HORIZONS
    assert h.bias_bps == pytest.approx(2.5)
    assert h.mae_bps == pytest.approx(3.5)
    assert h.rmse_bps == pytest.approx(math.sqrt(22.5))
    assert (h.directional_wins,h.directional_losses,h.zero_realized_return_count)==(2,1,1)
    assert h.directional_accuracy == pytest.approx(2/3)
    assert h.jeffreys_method == JEFFREYS_METHOD and h.status == "PROVISIONAL"
    with pytest.raises(Exception): state.symbol="BTC"
    shuffled=list(evidence); random.Random(2).shuffle(shuffled)
    again=build_accuracy_state(symbol="COIN",state_as_of=state.state_as_of,
                               cohorts=cohorts(),evidence=shuffled)
    assert again == state
    changed=list(evidence); changed[0]=(changed[0][0],replace(changed[0][1],actual_return_bps=1.5))
    assert build_accuracy_state(symbol="COIN",state_as_of=state.state_as_of,
        cohorts=cohorts(),evidence=changed).state_hash != state.state_hash


def test_directional_sign_matrix_and_zero_realized_return():
    samples = [
        (0.0, 2.0), (0.0, -2.0),
        (2.0, 2.0), (2.0, -2.0),
        (-2.0, -2.0), (-2.0, 2.0),
        (2.0, 0.0),
    ]
    evidence = []
    for i, (mu, y) in enumerate(samples):
        f = forecast("1M", i, mu)
        evidence.append((f, outcome(f, y)))
    horizon = build_accuracy_state(
        symbol="COIN", state_as_of=NOW + timedelta(days=1),
        cohorts=cohorts(), evidence=evidence,
    ).horizon_states[1]

    assert horizon.directional_wins == 2
    assert horizon.directional_losses == 4
    assert horizon.zero_realized_return_count == 1
    assert horizon.directional_accuracy == pytest.approx(1 / 3)
    assert horizon.directional_effective_n == 6
    assert horizon.effective_wins == pytest.approx(2)
    assert horizon.effective_losses == pytest.approx(4)
    assert horizon.jeffreys_posterior_mean == pytest.approx(2.5 / 7)
    assert horizon.jeffreys_lower is not None
    assert horizon.jeffreys_upper is not None
    assert horizon.jeffreys_interval_width == pytest.approx(
        horizon.jeffreys_upper - horizon.jeffreys_lower
    )
    assert horizon.status == "PROVISIONAL"


def test_unverified_evidence_excluded_and_horizons_degrade_independently():
    f=forecast("1M",0,2); pair=(f,outcome(f,1,False))
    state=build_accuracy_state(symbol="COIN",state_as_of=NOW+timedelta(days=1),cohorts=cohorts(),evidence=[pair])
    assert all(h.status == "UNAVAILABLE" for h in state.horizon_states)
    assert state.horizon_states[0].non_overlapping_n == 0


def test_preselected_overlap_preserves_frozen_accuracy_state_exactly():
    evidence = []
    for index in range(5):
        cutoff = NOW + timedelta(seconds=30 * index)
        item = replace(
            forecast("1M", index, 1.0),
            cutoff_at=cutoff,
            target_endpoint=cutoff + timedelta(seconds=60),
        )
        evidence.append((item, outcome(item, float(index + 1))))
    as_of = NOW + timedelta(hours=1)
    full = build_accuracy_state(
        symbol="COIN", state_as_of=as_of,
        cohorts=cohorts(), evidence=evidence,
    )
    selections = {}
    selected_evidence = []
    for horizon in HORIZONS:
        cohort_id, cohort_hash = cohorts()[horizon]
        governed = governed_accuracy_evidence(
            horizon, cohort_id, cohort_hash, as_of, evidence)
        selection = select_non_overlapping(governed)
        selections[horizon] = selection
        selected_ids = set(selection.selected_ids)
        selected_evidence.extend(
            pair for pair in governed
            if pair[0].forecast_record_id in selected_ids)

    streamed = build_accuracy_state(
        symbol="COIN", state_as_of=as_of, cohorts=cohorts(),
        evidence=selected_evidence, overlap_selections=selections,
    )

    assert streamed == full
    assert streamed.state_hash == full.state_hash
    assert streamed.horizon_states[1].raw_resolved_n == 5
    assert streamed.horizon_states[1].non_overlapping_n == 3


def test_effective_n_ips_and_metric_specific_sequences():
    assert effective_n([1,2])[0] == 2
    assert effective_n([1,1,1])[0] == 3
    assert "SERIAL_DEPENDENCE_UNIDENTIFIABLE" in effective_n([1,1,1])[1]
    dependent=[0,0,1,1,2,2,3,3,4,4]
    assert 1 <= effective_n(dependent)[0] < len(dependent)
    assert effective_n([0,1,0,1,0,1])[0] <= 6


def test_maturity_requires_both_effective_n_and_interval_width():
    evidence=[]
    for i in range(385):
        f=forecast("30S",i,1.0); evidence.append((f,outcome(f,1.0)))
    state=build_accuracy_state(symbol="COIN",state_as_of=NOW+timedelta(days=1),
                               cohorts=cohorts(),evidence=evidence)
    mature=state.horizon_states[0]
    assert mature.directional_effective_n == 385
    assert mature.jeffreys_interval_width <= .10 and mature.status == "MATURE"
    provisional=build_accuracy_state(symbol="COIN",state_as_of=NOW+timedelta(days=1),
        cohorts=cohorts(),evidence=evidence[:384]).horizon_states[0]
    assert provisional.status == "PROVISIONAL"


def test_zero_forecast_loss_propagates_through_mature_state():
    evidence=[]
    for i in range(385):
        mu, y = (0.0, -1.0) if i == 0 else (1.0, 1.0)
        f=forecast("30S",i,mu); evidence.append((f,outcome(f,y)))
    horizon=build_accuracy_state(symbol="COIN",state_as_of=NOW+timedelta(days=1),
        cohorts=cohorts(),evidence=evidence).horizon_states[0]
    assert (horizon.directional_wins, horizon.directional_losses) == (384, 1)
    assert horizon.directional_accuracy == pytest.approx(384 / 385)
    assert horizon.directional_effective_n == 385
    assert horizon.effective_wins == pytest.approx(384)
    assert horizon.effective_losses == pytest.approx(1)
    assert horizon.jeffreys_posterior_mean == pytest.approx(384.5 / 386)
    assert horizon.jeffreys_interval_width <= .10
    assert horizon.status == "MATURE"


class Cursor:
    def __init__(self, rows): self.rows=rows; self.sql=[]; self.closed=False
    def execute(self,sql,args): self.sql.append((sql,args))
    def fetchall(self): return self.rows.pop(0)
    def close(self): self.closed=True
class Connection:
    def __init__(self,rows):
        self.cursor_value=Cursor(rows); self.autocommit=False
        self.commits=0; self.rollbacks=0
    def cursor(self): return self.cursor_value
    def commit(self): self.commits+=1
    def rollback(self): self.rollbacks+=1


def test_store_idempotence_insert_and_same_time_conflict():
    empty=build_accuracy_state(symbol="COIN",state_as_of=NOW,cohorts=cohorts(),evidence=[])
    con=Connection([[],[]]); store=AccuracyStateStore(con)
    assert store.insert(empty,NOW)=="INSERT"
    assert "INSERT INTO atom_v9_v4_states" in con.cursor_value.sql[-1][0]
    assert (con.commits,con.rollbacks,con.cursor_value.closed)==(1,0,True)
    con=Connection([[(empty.state_hash,)]]); assert AccuracyStateStore(con).insert(empty,NOW)=="IDEMPOTENT"
    con=Connection([[('id-a','a',STATE_VERSION,MODEL_VERSION,'COIN','x',NOW,None,None,{}),
                     ('id-b','b',STATE_VERSION,MODEL_VERSION,'COIN','x',NOW,None,None,{})]])
    assert AccuracyStateStore(con).latest_json(symbol="COIN",cohort_id="x",requested_cutoff=NOW)[1]=="STATE_CONFLICT"


@pytest.mark.parametrize("index,replacement", [
    (0, "wrong-id"), (2, "wrong-state-version"), (3, "wrong-model-version"),
    (4, "QQQ"), (5, "wrong-cohort"), (6, NOW-timedelta(seconds=1)),
    (7, NOW), (8, NOW),
])
def test_latest_json_rejects_hash_valid_relational_metadata_mismatch(index, replacement):
    state=build_accuracy_state(symbol="COIN",state_as_of=NOW,cohorts=cohorts(),evidence=[])
    raw=json.dumps(_canonical(asdict(state)),sort_keys=True)
    row=[state.state_id,state.state_hash,state.state_version,state.model_version,
         state.symbol,state.cohort_id,state.state_as_of,None,None,raw]
    row[index]=replacement
    result=AccuracyStateStore(Connection([[tuple(row)]])).latest_json(
        symbol="COIN",cohort_id=state.cohort_id,requested_cutoff=NOW)
    assert result==(None,"STATE_DESERIALIZATION_INVALID")


def test_latest_json_rejects_hash_valid_future_payload_under_older_sql_time():
    state=build_accuracy_state(symbol="COIN",state_as_of=NOW+timedelta(seconds=1),
                               cohorts=cohorts(),evidence=[])
    raw=json.dumps(_canonical(asdict(state)),sort_keys=True)
    row=(state.state_id,state.state_hash,state.state_version,state.model_version,
         state.symbol,state.cohort_id,NOW,None,None,raw)
    assert AccuracyStateStore(Connection([[row]])).latest_json(
        symbol="COIN",cohort_id=state.cohort_id,requested_cutoff=NOW)==(
            None,"STATE_DESERIALIZATION_INVALID")
